import sys
import urllib
import urlparse
import xbmcgui
import xbmcplugin
import xbmcaddon
import json

__plugin__ =  'Channel9'
__author__ = 'Shawty/DS <shawty.d.ds@googlemail.com>'
__date__ = '07/07/2019'
__version__ = '0.1.0'
__settings__ = xbmcaddon.Addon(id='plugin.video.channel9')

# The following constant MUST be set to the root webserver where you have the JSON files stored
# if the plugin cannot download the JSON files generated by the tool over HTTP it will not work
JSON_ROOT_URL='http://MY.WEB.SERVER/CHANNEL9/'
PLUGIN_NAME='Channel9'

base_url = sys.argv[0]
addon_handle = int(sys.argv[1])
args = urlparse.parse_qs(sys.argv[2][1:])

xbmcplugin.setContent(addon_handle, 'movies')

def build_url(query):
  return base_url + '?' + urllib.urlencode(query)

def get_url_data(url):
  u = urllib.urlopen(url)
  data = u.read()
  return data  

def get_shows_list():

  pagelink=JSON_ROOT_URL+'showslist.json'
  pageJson=get_url_data(pagelink)
  return json.loads(pageJson)

def build_shows_list():

  showslist=get_shows_list()
  for show in showslist:
    url = build_url({'mode': 'show', 'showid': show["ShowId"]})
    listitem=xbmcgui.ListItem(show["DisplayName"], iconImage=show["ThumbHref"], thumbnailImage=show["ThumbHref"])
    listitem.setProperty('fanart_image', show["ThumbHref"])
    xbmcplugin.addDirectoryItem(handle = int(sys.argv[1]), url=url, listitem=listitem, isFolder=True)

def get_videos_list(videosjson):

  pagelink=JSON_ROOT_URL + videosjson
  pageJson=get_url_data(pagelink)
  return json.loads(pageJson)

def find_show_info(showid):

  showslist = get_shows_list()
  matchedshow = None
  for show in showslist:
    if show["ShowId"] == showid:
      matchedshow = show
      return matchedshow

  return None

def build_videos_list(showid):

  showinfo = find_show_info(showid)
  if showinfo == None:
    xbmcgui.Dialog().ok(__plugin__, "Unable to find show info for " + showid)
    return

  videoslist = get_videos_list(showinfo["VideosJsonFile"])
  for video in videoslist:
    
    li = xbmcgui.ListItem(video["VideoTitle"], iconImage=video["VideoPageThumb"])
    li.setProperty('fanart_image', video["VideoPageThumb"])
    xbmcplugin.addDirectoryItem(handle=addon_handle, url=video["ActualVideoFileLink"], listitem=li)



# Main runtime enters here
mode = args.get('mode', None)

#xbmcgui.Dialog().ok(__plugin__, pageJson)

if mode is None:
  build_shows_list()
  xbmcplugin.endOfDirectory(addon_handle)

elif mode[0] == 'show':
  showid = args['showid'][0]
  build_videos_list(showid)
  xbmcplugin.endOfDirectory(addon_handle)
